### PR TITLE
Fix control window while connecting ws

### LINKED ISSUE #27: Performance issues when not connected to an mhub bus
When the displaySystem is not connected to a websocket mhub bus, it still periodically tries to make a connection and fails. This is designed to make the system more robust to network glitches by automatically reconnecting.

However, while doing the websocket request, up until it times out, the application is not responsive to user input. You can verify this by opening up the network tab in the developer toolbar. Every time a request is pending, the application is unresponsive

### PR DESCRIPTION
**Pull request by rikkertkoppes**
Fixes #27 Now looking at the actual connected state while deciding where to send a message to

### CODE REVIEW

**Review by Jheronymus — APPROVED** [review]
Your second commit solves the problem completely. Unable to reproduce the reported issue on this branch.

File: modules/controls.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ displaySystem.registerModule({
                     btn.innerHTML = fn;
                     btn.addEventListener('click',function() {
                         var data = inps.map(getValue);
-                        if (system.ws) {
+                        if (system.ws && system.connected) {
```
Comment (poelstra) [inline modules/controls.js]: Can't we just check on `system.connected` (i.e. leave out 'system.ws`)?
That way we become independent of the usage of ws here (e.g. if we start using mhub-client in the future).

Comment (rikkertkoppes) [reply modules/controls.js]: Not sure, as `sendMessage` actually depends on system.ws

Comment (poelstra) [reply modules/controls.js]: Of course, but that's an 'internal detail' of sendMessage. As in: this piece of code doesn't depend on it?

In fact, probably that should be refactored in the future to something like `system.sendMessage()`, not `system.ws.sendMessage()` (inside the `sendMessage()` in this file).

Comment (rikkertkoppes) [reply modules/controls.js]: Not really, since if there is no ws, we'd want to call the method directly.

What about abstracting all that stuff in a system function call `if (system.connected()) {}`? That way, all things can be checked in the system itself.

Comment (poelstra) [reply modules/controls.js]: If there is no ws, then connected will also be false, right?
That's why I think testing for `system.ws` is redundant.

If more complicated (i.e. dynamic) stuff is required in the future, it would even be possible to convert `system.connected` to a getter.

**Review by Jheronymus — APPROVED** [review]
Latest change also fixes the problem
